services:
  - type: web
    name: lumina-pro-server
    env: node
    region: oregon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: Lumina612@2007
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
