-- Run this SQL in Supabase SQL editor to create the users and subscriptions tables
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  username text not null,
  plan text not null,
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_username ON public.subscriptions (username);
